"""Validate task files and build deterministic Worker/static catalog artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import pprint
from pathlib import Path

from jsonschema import Draft202012Validator, FormatChecker

ROOT = Path(__file__).resolve().parents[1]
TASKS_DIR = ROOT / "catalog" / "tasks"
SCHEMA_PATH = ROOT / "schema" / "translation-task-v1.schema.json"
PUBLIC_CATALOG = ROOT / "public" / "tasks.json"
PUBLIC_SCHEMA = ROOT / "public" / "schema" / SCHEMA_PATH.name
PYTHON_CATALOG = ROOT / "src" / "translation_hub" / "generated_catalog.py"


def load_tasks() -> list[dict[str, object]]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    tasks: list[dict[str, object]] = []
    seen: set[str] = set()

    for path in sorted(TASKS_DIR.glob("*.json")):
        task = json.loads(path.read_text(encoding="utf-8"))
        errors = sorted(validator.iter_errors(task), key=lambda item: list(item.path))
        if errors:
            details = "\n".join(
                f"{path.relative_to(ROOT)}:{'/'.join(map(str, error.path))}: {error.message}"
                for error in errors
            )
            raise ValueError(details)
        task_id = str(task["id"])
        if task_id in seen:
            raise ValueError(f"duplicate task id: {task_id}")
        if path.stem != task_id:
            raise ValueError(f"{path.relative_to(ROOT)} must be named {task_id}.json")
        seen.add(task_id)
        tasks.append(task)

    if not tasks:
        raise ValueError("catalog must contain at least one task")
    return tasks


def render(tasks: list[dict[str, object]]) -> dict[Path, str]:
    canonical = json.dumps(tasks, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    revision = hashlib.sha256(canonical.encode()).hexdigest()
    collection = {
        "schema_version": "translation-task-collection/v1",
        "catalog_revision": revision,
        "total": len(tasks),
        "items": tasks,
    }
    public_json = json.dumps(collection, ensure_ascii=False, indent=2) + "\n"
    python_literal = pprint.pformat(tasks, width=100, sort_dicts=False)
    python_source = (
        "# ruff: noqa\n"
        '"""Generated by scripts/build_catalog.py. Do not edit directly."""\n\n'
        f'CATALOG_REVISION = "{revision}"\n'
        f"TASKS = {python_literal}\n"
    )
    return {
        PUBLIC_CATALOG: public_json,
        PUBLIC_SCHEMA: SCHEMA_PATH.read_text(encoding="utf-8"),
        PYTHON_CATALOG: python_source,
    }


def write_or_check(outputs: dict[Path, str], *, check: bool) -> None:
    stale: list[str] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("generated catalog is stale: " + ", ".join(stale))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tasks = load_tasks()
    write_or_check(render(tasks), check=args.check)
    print(f"catalog valid: {len(tasks)} tasks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
